#+TITLE: bosabosa
#+STARTUP: logdone
#+HUGO_BASE_DIR: ./

* Posts
:PROPERTIES:
:EXPORT_HUGO_SECTION: posts
:EXPORT_HUGO_AUTO_SET_LASTMOD: t
:END:
** DONE First Post
CLOSED: [2018-10-18 Thu 16:31]
:PROPERTIES:
:EXPORT_FILE_NAME: first-post
:END:
:LOGBOOK:
- State "DONE"       from "TODO"       [2018-10-18 Thu 16:31] \\
  First post!
:END:
 Hello, World!
** DONE Make a Website
CLOSED: [2018-10-18 Thu 19:46]
:LOGBOOK:
- State "DONE"       from "TODO"       [2018-10-18 Thu 19:46] \\
  It's up, so this is not TODO. Although it can be better :)
:END:
:PROPERTIES:
#+HUGO_AUTO_SET_LASTMOD: t
:EXPORT_FILE_NAME: make-a-website
:END:
#+begin_details
#+begin_summary
In this post, you will learn what powers this website and how you can create your own in a few minutes.
#+end_summary
I built this website with hugo, a static site generator. The contents are kept in a single file.
#+end_details

*** Overview
 This is the overview of how my site works.

# Insert diagram here.

*** Browse Source

The source code to this site is open and available on [[https://github.com/dds/www.bosabosa.org][github]].

** TODO Re: André Staltz - Reinvent the Social Web
:PROPERTIES:
:EXPORT_FILE_NAME: reinvent-the-social-web
:SOURCE: [[https://staltz.com/reinvent-the-social-web.html][André Staltz - Reinvent the Social Web]]
:CAPTURED: [2018-10-18 Thu 18:25]
:END:

*** Background

André posts about a protocol and app for reinventing the social web in a decentralized way that might just work. The specifics are using the [[https://www.scuttlebutt.nz/][scuttlebut]] social syncing protocol, the [[https://github.com/auditdrivencrypto/secret-handshake][secret-handshake]] mutual authentication scheme, the [[https://github.com/ssbc/patchwork][patchwork]] interface that looks like a better email/facebook communication tool, instagram-like [[https://github.com/ssbc/patchbay][patchbay]], [[https://github.com/ticktackim/ticktack-network][ticktack]] blogging platform, and [[https://www.manyver.se/][manyver.se]] mobile client.

*** Field Report

Ok, let's try it out.


** TODO We all Struggle
:PROPERTIES:
:EXPORT_FILE_NAME: we-all-struggle
:END:

** TODO Shame and Pride
:PROPERTIES:
:EXPORT_FILE_NAME: shame-and-pride
:END:
#+begin_summary
Shame is hard to give up, but if you have it, make it a priority to get rid of it.

 - Fuck pride

 - Just be you and own it

 - It's OK to ask for help along the way

#+end_summary
#+begin_quote
Be so great, they can't ignore you.

-- Steve Martin
#+end_quote

How do you feel about yourself? Are you proud? I hope you are a little, because you're the shit. You're reading this, so you've learned to read and had to overcome incredible odds and adversity to do that, and so much more. How proud are you?

Because pride can send you into a dark place, too. Do you think you're better than others? If you sometimes catch yourself thinking, "why can't he just figure it out?" or, "why doesn't she know this already?" then you might be too proud. Since [[/posts/we-all-struggle][we all struggle]], we don't all get there at the same pace, if at all.

* About
:PROPERTIES:
:EXPORT_HUGO_SECTION: /
:EXPORT_FILE_NAME: about
:EXPORT_HUGO_MENU: :menu "main" :title "About"
:EXPORT_DATE: [2018-10-18 Thu 16:31]
:CUSTOM_ID: about

:END:
** Who am I?

My name is David Daniel Smith and this is my personal website.

** Where have I been? Where am I? And where am I going?
** What is this site?
** Why do I do this?
I like serving my own website instead of using commercial providers. I have done it in various ways since 1999.

** How does this site work?

I wrote a post about [[/posts/make-a-website][how to make a website]] that guides you through creating your own simple website using the same system as this one. It's not as simple as signing up for facebook, but it's close.

# Local Variables:
# org-hugo-auto-export-on-save: t
# End:
