baseURL                 = "https://www.bosabosa.org/"
title                   = "bosabosa"
copyright               = "Copyright &copy; 2010-2018 David Smith"
canonifyurls            = true
isMultilingual          = true
defaultContentLanguage  = "en"
languageCode            = "en-us"
googleAnalytics         = "UA-1916871-6"
paginate                = 5
summaryLength           = 30
enableEmoji             = true
pygmentsCodeFences      = true
cleanDestinationDir     = true

[author]
  name = "David Daniel Smith (dds)"
  github = "dds"
  gitlab = "daviddanielsmith"
  twitter = "exponent"

[params]
  tagline = "Hello, World!"
  mainSections = ["posts"]

[permalinks]
  posts = "/:year/:month/:slug/"
  
[menu]

  [[menu.main]]
  identifier = "posts"
  name = "Posts"
  url = "/posts/"
  weight = 1
  
